# Generated by Django 5.0.4 on 2024-04-30 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0001_initial'),
        ('tasks', '0002_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugreport', to='tasks.project'),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugreport', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_request', to='tasks.project'),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_request', to='tasks.task'),
        ),
    ]
